sudo: required
services:
  - docker

addons:
  apt:
    packages:
    - docker-ce

before_install:
  - docker build -t erebe/hmailclassifier .

script:
  - docker run --rm -ti -v $(pwd):/mnt erebe/hmailclassifier /bin/sh -c 'cp hmailclassifier /mnt'

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: sPjBU2/iOh73MRfwLh9FbfqyCAlLPQAPJw6sakEhYa2WEc8VlNtQn0PdhdkfxlbRqa9IzpbXoEq3ITMwmaGoAXSLHlY4JzMLDJs6V9QI6KSjEkavQ+u5DvLz1LEsL8CgKuA8/BZ77Y0VjvCHj0iTfjqXy17dRsjYuBEkAc4Ord/Afkj9PGa6kmChc1v5sjULtum94RxhjgGBlwHxNg/W8p5UiPB5yDuP8x3UKO2VNjVLQoxMJP9cWGYBfwZQXP44cbZMJds1VH+jMCsnmqzg20JamukjnDOYaqDDac+DwpafHGL1tjzscXzOJA4S+kU98etgSzH+CcXQM5A/651Oig9jxoT2YME0Hym5H7lgVWItDr5SLe2/O5TFQZxTmGkX4rQl6bbM4Yf1PawZnNiU7/U00Zp27RdjS1dSLwPyBfObt+n2aQttR7LAIGxNbQXNcP7B9J/DyL2KOJw9VoWNATcGbvnFS1ACRKuHPCVkdhqA2IhQSGdG5kQP8zSuXYSqb3Bck11DdRxoJhcQy7IXhP9hvs4Hq1fhf6H9x1DGxqqur6Ew2m/hDZ8fhcATYrWrgYxg1W7XF1VZbHJQJnJ9h76CLBxzCS7ANBuaBcUHOcDe0yqGYWarohhmkhymEwSATwJT5dxFuwFEpZkeTP3axSzg16zL3emjMmiqdjGg/54=
  file: greenclip
  on:
    tags: true
