- hosts: server
  remote_user: root

  vars:
    user: erebe

  tasks:
    ################################
    # APP
    ################################
    - name: Install hmailfilter
      copy: src=config/hmailclassifier
            dest=/usr/local/bin/
            owner={{ user }}
            group={{ user }}
            mode=u=rx,g=rx,o=rx

    - name: Add {{ user }} config
      template: src=config/procmailrc
                dest=/home/{{ user }}/.procmailrc
                owner={{ user }}
                group={{ user }}
                mode=u=r,g=r,o=r

    ################################
    # SYSTEMD
    ################################
    - name: Copy systemd service
      template: src=config/purgemailbox@.service
                dest=/usr/lib/systemd/system/

    - name: Copy systemd timer
      template: src=config/purgemailbox@.timer
                dest=/usr/lib/systemd/system/

    - name: reload systemd
      command: systemctl daemon-reload

    - name: purgemailbox timer started
      service: name=purgemailbox@{{ user }}.timer state=started enabled=true

