name: Build bot

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        docker build -t hmailfilter .
        docker run --rm -v $(pwd):/data hmailfilter /bin/cp /root/hmailclassifier /data

    - uses: actions/upload-artifact@v1
      with:
        name: hmailclassifier
        path: hmailclassifier

