name: Build bot

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.3'
        cabal-version: '3.0'
       
    - name: Build
      run: |
        docker build -t hmailfilter .
        docker run --rm -v $(pwd):/data hmailfilter /bin/cp /root/.local/bin/hmailclassifier /data

    - uses: actions/upload-artifact@v1
      with:
        name: hmailclassifier
        path: /root/hmailclassifier

